#!/bin/bash

set -xe

if type apt-get > /dev/null 2>&1; then
  sudo apt-get install -y stow exuberant-ctags
elif type brew > /dev/null 2>&1; then
  brew install stow
fi

cd ~/dotfiles
git submodule update --init --recursive
stow files

if ! grep -q '^. ~/.bashrc.d/.all.sh$' ~/.bashrc; then
  printf '\n. ~/.bashrc.d/.all.sh\n' >> ~/.bashrc
fi

cp -nr defaults/ ~
