#!/bin/bash

set -xe

repo_dir=$(dirname "${BASH_SOURCE[0]}")

if type apt-get > /dev/null 2>&1; then
  sudo apt-get install -y stow exuberant-ctags
elif type brew > /dev/null 2>&1; then
  brew install stow
fi

cd "$repo_dir"
git submodule update --init --recursive
stow --target="$HOME" files

if ! grep -q '^. ~/.bashrc.d/.all.sh$' ~/.bashrc; then
  printf '\n. ~/.bashrc.d/.all.sh\n' >> ~/.bashrc
fi

cp -nr defaults/ ~
