#!/bin/bash

if type apt-get > /dev/null 2>&1; then
  sudo apt-get install stow
elif type brew > /dev/null 2>&1; then
  brew install stow
fi

# For spin setup
if [ -f ~/.gitconfig -a ! -L ~/.gitconfig -a ! -f ~/.gitconfig-local ]; then
  mv -n ~/.gitconfig ~/.gitconfig-local
fi

cd ~/dotfiles
stow files
